name: Docker Pull

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker image build -t koa-demo .

      - name: Run Docker Container
        run: docker container run --rm -p 8001:3000 -it koa-demo
      
