name: Docker Pull

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Docker Pull
      run: |
        docker container run --rm -p 8001:3000 -it kentblx/test:v1
